In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def fft1d(m):
  fft1d = np.zeros([m, m], dtype=complex)
  for u in range(m):
    for x in range(m):
      fft1d[u][x] = np.round(np.exp(-1j*2*np.pi*x*u/m), 10)
  ifft1d = np.conj(fft1d)
  return fft1d, ifft1d

In [ ]:
def dct1d(N):
  dct_d = np.zeros([N, N])

  for k in range(N):
    for n in range(N):
      dct_d[k, n] = np.cos(np.pi*((n+0.5)/N * k))
  return dct_d

In [ ]:
def walsh1d(N):
  def getBinaries(n):
    binary = [int(x) for x in bin(n)[2:]]
    return [0]*(int(np.log2(N))-len(binary)+1) + binary
  G1d = np.zeros([N, N])
  for x in range(N):
    for u in range(N):
      bx = getBinaries(x)
      bu = getBinaries(u)
      G1d[x, u] = (-1) ** sum(np.multiply(bx, bu[::-1]))
  return G1d

In [ ]:
def hadamard1d(N):
  def getBinaries(n):
    binary = [int(x) for x in bin(n)[2:]]
    return [0]*(int(np.log2(N))-len(binary)+1) + binary
  H1d = np.zeros([N, N])
  for x in range(N):
    for u in range(N):
      bx = getBinaries(x)
      bu = getBinaries(u)
      H1d[x, u] = (-1) ** sum(np.multiply(bx, bu))
  return H1d

In [ ]:
def convolve_2D(image, kernel):
    return ccorrelation_2d(image, np.flipud(np.fliplr(kernel)))

def ccorrelation_2d(image, kernel):
    padding = kernel.shape[0] - 1

    # Shape of Output Convolution
    xOutput = int(((image.shape[0] - kernel.shape[0] + 2 * padding) ) + 1)
    yOutput = int(((image.shape[1] - kernel.shape[1] + 2 * padding) ) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides

    imagePadded = np.pad(image, padding)

    # Iterate through image
    for y in range(yOutput):
        for x in range(xOutput):
            output[x, y] = np.sum(kernel * imagePadded[x: x + kernel.shape[0], y: y + kernel.shape[1]])
    return output

In [ ]:
convolve_2D(np.array([[1, 2, 1], [1, 2, 1], [3, 3, 3]]), np.array([[1, 1], [-1, -1]]))

array([[ 1.,  3.,  3.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 2.,  3.,  3.,  2.],
       [-3., -6., -6., -3.]])

In [ ]:
robertsFilterx = np.array([[1, 0], [0, -1]])
robertsFiltery = np.flipud(robertsFilterx).transpose()

sobelFilterx = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
sobelFiltery = np.flipud(sobelFilterx).transpose()

prewittFilterx = np.array([[-1, 0, 1]]*3)
prewittFiltery = np.flipud(prewittFilterx).transpose()
print(prewittFiltery)

[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]


In [ ]:
def histEqualization(image):
  hist, _ = np.histogram(img.flatten(), bins=range(257))
  pdf = hist / (256 ** 2)
  cdf = np.zeros(257)
  for i in range(256):
    cdf[i] = cdf[i-1] + pdf[i]
    cdf[i] = 1 if cdf[i] > 1 else cdf[i]
  cdf = cdf * 255
  cdf = np.floor(cdf)
  new_image = np.zeros(img.shape)
  for i in range(img.shape[0]):
    for j in range(img.shape[1]):
      new_image[i, j] = cdf[img[i, j]]
  return new_image, cdf

In [ ]:
equal1 = histEqualization(origImage)[1]
equal2 = histEqualization(targetImage)[1]
list(map(lambda eq1val: np.where(equal2 >= eq1val)[0][0], equal1))

In [ ]:
def imgClip(img, thresh):
  img[img<thresh] = 0
  return img
def imgWindow(img, window):
  img[img>window] = 0
  return img